# .github/workflows/treebeard.yml
# Run all notebooks on every push and weekly
name: tutorials
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        notebook: ['00_simple_example', '02_Eigendistortions', '01_Linear_approximation_of_nonlinear_model', '03_Steerable_Pyramid', '04_Perceptual_distance', '05_Geodesics', '06_Metamer', '07_MAD_Competition', '08_Simple_MAD', '09_Original_MAD', '10_Synthesis', 'Display']
      fail-fast: false
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # based on AllenNLP's setup:
      # https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
      - name: Cache environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager -e .
          sudo apt update
          sudo apt install ffmpeg
          pip install jupyter
          pip install ipywidgets
      - uses: treebeardtech/treebeard@master
        with:
          use-docker: false
          notebooks: 'examples/${{ matrix.notebook }}.ipynb'
